spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reliable-group
      enable-auto-commit: false # Manual acknowledgment
      listener:
      ack-mode: manual_immediate # Allows fine-grained acknowledgment handling
    producer:
      retries: 5 # Retries for transient failures
